name: longsplice
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
# --- Python base
 - python=3.12
 - pip
 - git
 - numpy
 - scipy
 - scikit-learn>=1.3,<1.6
 - r-xgboost=1.7.*
# --- CLI & libs
 - minimap2=2.28
 - samtools=1.21
 - bedtools=2.31.1
 - bedops=2.4.41
 - ucsc-bedtobigbed
 - hmmer
 - openjdk
# --- R / Bioconductor (nÃºcleo)
 - r-base
 - r-biocmanager
 - bioconductor-biocparallel
 - bioconductor-deseq2
 - bioconductor-drimseq
 - bioconductor-dexseq
 - bioconductor-stager
 - bioconductor-bambu
 - bioconductor-rsamtools
 - bioconductor-bsgenome
 - bioconductor-isoformswitchanalyzer
 - bioconductor-tximport
# --- R (CRAN, utilidades y plotting)
 - r-argparse
 - r-optparse
 - r-data.table
 - r-readr
 - r-dplyr
 - r-tidyr
 - r-ggplot2
 - r-scales
 - r-pheatmap
 - r-openxlsx
 - r-rmarkdown
 - r-knitr
 - r-qqman
# --- Py ecosystem
 - nanoplot
 - pysam=0.22.1
 - pyarrow
 - multiqc=1.14
 - deeptools
 - pybigwig
 - matplotlib
 - plotly
 - python-kaleido
 - seaborn
 - pybedtools=0.11.0
 - ncls=0.0.68
 - pipettor=1.2.1
 - bioconda::mappy>=2.28
# --- Preprocessing & QC tools
 - fastqc=0.12.1
 - fastp=0.23.4
 - bowtie2=2.5.4
# --- Pychopper dependencies (biopython desde conda, resto desde pip)
 - biopython
 - pip:
   - edlib
   - parasail
   - "flair-brookslab @ git+https://github.com/BrooksLabUCSC/flair.git@master"
   - "git+https://github.com/epi2me-labs/pychopper.git@v2.7.1"